#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#RUTAS CONTROLADOR USUARIO#
img:
    path: /img/{imagen}
    controller: App\Controller\UsuarioController::recogerimagen
    methods: [GET]
usuario:
    path: /usuario
    controller: App\Controller\UsuarioController::index
registro:
    path: /registro
    controller: App\Controller\UsuarioController::create
    methods: [POST]
login:
    path: /login
    controller: App\Controller\UsuarioController::login
    methods: [POST]
update:
    path: /update
    controller: App\Controller\UsuarioController::update
    methods: [POST]

upload:
    path: /upload/{id}
    controller: App\Controller\UsuarioController::upload
    methods: [POST]

findById:
    path: /findById
    controller: App\Controller\UsuarioController::findById
    methods: [POST]
putUsuario:
    path: /putUsuario
    controller: App\Controller\UsuarioController::putUsuario
    methods: [PUT]
#RUTAS CONTROLADOR ADMINISTRADOR
admin:
    path: /admin
    controller: App\Controller\AdministradorController::index
createAdmin:
    path: /createAdmin
    controller: App\Controller\AdministradorController::createAdmin
    methods: [POST]
deleteUser:
    path: /deleteUser/{id}
    controller: App\Controller\AdministradorController::deleteUser
    methods: [DELETE]
list:
    path: /list
    controller: App\Controller\UsuarioController::findAll
    methods: [POST]


#RUTAS CONTROLADOR ESPECIALIDADES
esspecialidades:
    path: /especialidades
    controller: App\Controller\EspecialidadController::getEspecialidades
    methods: [GET]

#RUTAS CONTROLADOR HORARIOS
horarios:
    path: /createHorario
    controller: App\Controller\HorarioController::createHorario
    methods: [POST]


#RUTAS CONTORLADOR DIAS
dias:
    path: /createDia
    controller: App\Controller\DiaController:createDia
    methods: [POST]

#RUTAS CONTROLADOR MEDICOS
updateMedico:
    path: /updateMedico
    controller: App\Controller\MedicoController::update
    methods: [POST]
consultaCitas:
    path: /consultaCitasMedico
    controller: App\Controller\MedicoController::consultarCitas
    methods: [POST]
buscarMedicos:
    path: /buscarMedicosEspecialidad
    controller: App\Controller\MedicoController::buscarMedicos
    methods: [POST]


#RUTAS CONTROLADOR CITAS
createCita:
    path: /createCita
    controller: App\Controller\CitaController::create
    methods: [POST]

#RUTAS CONTROLADOR PACIENTES
find:
    path: /findPaciente/{id}
    controller: App\Controller\PacienteController::findPaciente
    methods: [GET]
put:
    path: /putPaciente
    controller: App\Controller\PacienteController::putPaciente
    methods: [PUT]

#RUTAS CONTROLADOR INFORMES
create:
    path: /createInforme
    controller: App\Controller\InformeController::createInforme
    methods: [POST]
getInformes:
    path: /getInformes/{id}
    controller: App\Controller\InformeController::getInformes
    methods: [GET]
getInformesMedico:
    path: /getInformesPorMedico/{id}
    controller: App\Controller\InformeController::getInformesPorMedico
    methods: [GET]
buscarInformes:
    path: /buscarInformes
    controller: App\Controller\InformeController::buscarInformes
    methods: [POST]

#RUTAS CONTROLADOR HABITACIONES
getHabitacion:
    path: /getHabitacion
    controller: App\Controller\HabitacionController::getHabitacion
    methods: [GET]
putHabitacion:
    path: /putHabitacion
    controller: App\Controller\HabitacionController::putHabitacion
    methods: [PUT]

#RUTAS CONTROLADOR INGRESOS
createIngreso:
    path: /createIngreso
    controller: App\Controller\IngresoController::createIngreso
    methods: [POST]
findIngreso:
    path: /findIngreso/{id}
    controller: App\Controller\IngresoController::findIngreso
    methods: [GET]
putIngreso:
    path: /putIngreso
    controller: App\Controller\IngresoController::putIngreso
    methods: [PUT]

